version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::383769736888:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1M1YTERJRFDUV"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::383769736888:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-15CF16OD6FIIT"
cloudformation_execution_role = "arn:aws:iam::383769736888:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1W544B8KH2V4N"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-sri9ec97urri"
image_repository = ""
region = "sa-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::383769736888:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-GH633SPUU5J9"
cloudformation_execution_role = "arn:aws:iam::383769736888:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-3Z2MTOAWG8TL"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1fhy256gak5sw"
image_repository = ""
region = "sa-east-1"
